# Autogenerated wrapper script for CUDA_Driver_jll for x86_64-linux-gnu
export libcuda, libnvidia_ptxjitcompiler

JLLWrappers.@generate_wrapper_header("CUDA_Driver")
JLLWrappers.@declare_library_product(libcuda, "libcuda.so.1")
JLLWrappers.@declare_library_product(libnvidia_ptxjitcompiler, "libnvidia-ptxjitcompiler.so.1")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libcuda,
        "lib/libcuda.so",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libnvidia_ptxjitcompiler,
        "lib/libnvidia-ptxjitcompiler.so.1",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
    global version = v"11.8.0"

end  # __init__()
